@echo off
echo Starting Learning Platform Project...

echo Starting Backend Server...
cd BackEnd
start cmd /k "npm run dev"

echo Starting Frontend Server...
cd ../LearingPlatform
start cmd /k "npm run dev"

echo Servers are starting in new windows...
